routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
});

Auth::routes();

Route::group(['prefix' => 'isAdmin', 'middleware' => ['admin', 'auth']], function(){
	Route::get('/admin', 'AdminController@index')->name('admin.index');
	Route::resource('users', 'UserController');
	Route::resource('bengkel', 'BengkelController');
	Route::resource('streets', 'StreetController');
});

Route::resource('home', 'HomeController');

app/Bengkel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Street;

class Bengkel extends Model
{
    protected $table = "bengkel";

    protected $guarded = [];

    public function street()
    {
        return $this->belongsTo(Street::class, 'street_id', 'id');
    }

    public function service()
    {
        return $this->belongsToMany('App\Service');
    }
}

app/Http/Controllers/BengkelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Bengkel;
use App\Street;

class BengkelController extends Controller
{
    public function index()
    {
    	$bengkel = Bengkel::all();
    	return view('bengkel.index', compact('bengkel'));
    }

    public function show($id)
    {
    	$bengkel = Bengkel::findOrFail($id);
    	return view('bengkel.show', compact('bengkel'));
    }

    public function create()
    {
    	$streets = Street::all();
    	return view('bengkel.create', ['streets'=>$streets]);
    }

    public function store(Request $request)
    {
    	$request->validate([
    		'nama_bengkel'	=> 'required',
    		'jenis_bengkel'	=> 'required',
    		'no_usaha'		=> 'required',
    		'street_id'		=> 'required',
    	]);

    	Bengkel::create([
    		'nama_bengkel'	=> $request->nama_bengkel,
    		'jenis_bengkel'	=> $request->jenis_bengkel,
    		'no_usaha'		=> $request->no_usaha,
    		'street_id'		=> $request->street_id,
    	]);

    	return redirect()->route('bengkel.index');
    }

    public function edit($id)
    {
    	$bengkel = Bengkel::findOrFail($id);
    	$streets = Street::all();
    	return view('bengkel.edit', ['bengkel'=>$bengkel, 'streets'=>$streets]);
    }

    public function update(Request $request, $id)
    {
    	$bengkel = Bengkel::findOrFail($id);
    	$request->validate([
    		'nama_bengkel'	=> 'required',
    		'jenis_bengkel'	=> 'required',
    		'no_usaha'		=> 'required',
    		'street_id'		=> 'required',
    	]);

    	$bengkel->update([
    		'nama_bengkel'	=> $request->nama_bengkel,
    		'jenis_bengkel'	=> $request->jenis_bengkel,
    		'no_usaha'		=> $request->no_usaha,
    		'street_id'		=> $request->street_id,
    	]);

    	return redirect()->route('bengkel.index', ['bengkel'=>$bengkel]);
    }

    public function destroy($id)
    {
    	$bengkel = Bengkel::findOrFail($id);
    	$bengkel->delete();
    	return redirect()->back();
    }
}

resources/views/bengkel/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
    <div class="card">
        <div class="card-header bg-info text-light">
            Create New Bengkel
        </div>

        <div class="card-body">
            <form class="form-group" action="{{ route('bengkel.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

                <div class="row">
                    <div class="col-md-2">
                        <label for="nama_bengkel">Nama Bengkel</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control {{$errors->first('nama_bengkel')? "is-invalid": ""}}" value=" {{ old('nama_bengkel') }} " id="nama_bengkel" name="nama_bengkel">
                        <div class="invalid-feedback">
                          {{$errors->first('nama_bengkel')}}
                        </div>
                    </div>
                </div>

              <br>

                <div class="row">
                    <div class="col-md-2">
                        <label for="jenis_bengkel">Jenis Bengkel</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control {{$errors->first('jenis_bengkel')? "is-invalid": ""}}" value=" {{ old('jenis_bengkel') }} " id="jenis_bengkel" name="jenis_bengkel">
                        <div class="invalid-feedback">
                          {{$errors->first('jenis_bengkel')}}
                        </div>
                    </div>
                </div>

              <br>

                <div class="row">
                    <div class="col-md-2">
                        <label for="no_usaha">No Usaha</label>
                    </div>
                    <div class="col-md-9">
                        <input type="number" class="form-control {{$errors->first('no_usaha')? "is-invalid": ""}} " id="no_usaha" name="no_usaha" value=" {{old('no_usaha')}} ">
                        <div class="invalid-feedback">
                          {{$errors->first('no_usaha')}}
                        </div>
                    </div>
                </div>

              <br>

                <div class="row">
                    <div class="col-md-2">
                        <label for="street_id">Alamat</label>
                    </div>
                    <div class="col-md-9">
                        <select name="street_id" id="street_id" class="form-control {{$errors->first('street_id')? "is-invalid": ""}} ">
                            <option value="">Alamat</option>
                                @foreach($streets as $street)
                                    <option value=" {{$street->id}} ">
                                        {{$street['nama_jalan']}}
                                    </option>
                                @endforeach
                        </select>
                        <div class="invalid-feedback">
                            {{$errors->first('street_id')}}
                        </div>
                    </div>
                </div> 

              <br>

                <div class="row">
                    <div class="col-md-3 offset-md-5 offset-md-4">
                        <button class="btn btn-outline-info" type="submit">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/bengkel/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
    <div class="card">
        <div class="card-header bg-info text-light">
            Edit Bengkel
        </div>

        <div class="card-body">
            <form class="form-group" action="{{ route('bengkel.update', $bengkel['id']) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')

                <div class="row">
                    <div class="col-md-2">
                        <label for="nama_bengkel">Nama Bengkel</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control {{$errors->first('nama_bengkel')? "is-invalid": ""}}" id="nama_bengkel" name="nama_bengkel" value=" {{ old('nama_bengkel') ? old('nama_bengkel') : $bengkel['nama_bengkel'] }} ">
                        <div class="invalid-feedback">
                          {{$errors->first('nama_bengkel')}}
                        </div>
                    </div>
                </div>

            <br>

                <div class="row">
                    <div class="col-md-2">
                        <label for="jenis_bengkel">Jenis Bengkel</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control {{$errors->first('jenis_bengkel')? "is-invalid": ""}}" id="jenis_bengkel" name="jenis_bengkel"  value=" {{ old('jenis_bengkel') ? old('jenis_bengkel') : $bengkel['jenis_bengkel'] }} ">
                        <div class="invalid-feedback">
                          {{$errors->first('jenis_bengkel')}}
                        </div>
                    </div>
                </div>

            <br>

                <div class="row">
                    <div class="col-md-2">
                        <label for="no_usaha">No Usaha</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control {{$errors->first('no_usaha')? "is-invalid": ""}}" id="no_usaha" name="no_usaha" value=" {{old('no_usaha') ? old('no_usaha') : $bengkel['no_usaha'] }} ">
                        <div  class="invalid-feedback">
                            {{$errors->first('no_usaha')}}
                        </div>
                    </div>
                </div>

            <br>

                <div  class="row">
                    <div class="col-md-2">
                        <label for="street_id">Alamat</label>
                    </div>
                    <div class="col-md-9">
                        <select name="street_id" id="street_id" class="form-control {{$errors->first('street_id')? "is-invalid": ""}} ">
                            <option value="">Alamat</option>
                                @foreach($streets as $s)
                                    <option value=" {{$s->id}} " {{$bengkel->street_id==$s->id ? "selected": ''}}>
                                        {{$s->nama_jalan}}
                                    </option>
                                @endforeach
                        </select>
                        <div class="invalid-feedback">
                            {{$errors->first('street_id')}}
                        </div>
                    </div>
                </div>

            <br>

                <div class="row">
                    <div class="col-md-3 offset-md-5 offset-md-4">
                        <button class="btn btn-outline-primary" type="submit">Simpan</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection

resources/views/bengkel/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
    <div class="card">
        <div class="card-header">
            Bengkel
        </div>

        <div class="card-body">
            <a href="{{ route('bengkel.create') }}" class="btn btn-success"><span data-feather="plus-square"></span> Create new</a>
            <br><br>

            <div class="tabel-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr class="table-success">
                            <th>ID</th>
                            <th>Nama Bengkel</th>
                            <th>Jenis Bengkel</th>
                            <th>Alamat</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($bengkel as $beng)
                            <tr>
                                <td> {{$beng['id']}} </td>
                                <td> {{$beng['nama_bengkel']}} </td>
                                <td> {{$beng['jenis_bengkel']}} </td>
                                <td> {{$beng->street->nama_jalan}} </td>
                                <td>
                                    <a href="{{ route('bengkel.show', ['id'=>$beng['id']]) }}" class="btn-sm btn-success">Detail</a>
                                    <a href="{{ route('bengkel.edit', ['id'=>$beng['id']]) }}" class="btn-sm btn-primary">Edit</a>
                                    
                                    <form action="{{ route('bengkel.destroy', ['id'=>$beng['id']]) }}" method="POST" onsubmit="return confirm('Delete Permanen?')" class="d-inline">
                                      @csrf
                                      @method('DELETE')

                                      <button type="submit" class="btn-xs btn-danger" name="submit" value="Delete" style="border: none; border-radius: 3px;">
                                          Delete
                                      </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/bengkel/show.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
	<div class="card">
		<div class="card-header bg-info text-light">
			Detail Bengkel
		</div>

		<div class="card-body">

			<div class="row">
				<div class="col-md-2">
					<label for="nama_bengkel">Nama Bengkel</label>
				</div>
				<div class="col-md-9">
					<input type="text" readonly="" value="{{$bengkel['nama_bengkel']}}" class="form-control">
				</div>
			</div>

			<br>

			<div class="row">
				<div class="col-md-2">
					<label for="jenis_bengkel">Jenis Bengkel</label>
				</div>
				<div  class="col-md-9">
					<input type="text" value="{{$bengkel['jenis_bengkel']}}" class="form-control" readonly="">
				</div>
			</div>

			<br>

			<div class="row">
				<div class="col-md-2">
					<label for="no_usaha">No Usaha</label>
				</div>
				<div class="col-md-9">
					<input type="text" value=" {{$bengkel['no_usaha']}} " class="form-control" readonly="">
				</div>
			</div>

			<br>

			<div class="row">
				<div class="col-md-2">
					<label for="street_id">Alamat</label>
				</div>
				<div class="col-md-9">
					<input type="text" value=" {{$bengkel->street->nama_jalan}} " class="form-control" readonly="">
				</div>
			</div>

		</div>

	</div>
</div>

@endsection