routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
});

Auth::routes();

Route::group(['prefix' => 'isAdmin', 'middleware' => ['admin', 'auth']], function(){
	Route::get('/admin', 'AdminController@index')->name('admin.index');
	Route::resource('users', 'UserController');
	Route::resource('bengkel', 'BengkelController');
	Route::resource('streets', 'StreetController');
});

Route::resource('home', 'HomeController');

app/Street.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Bengkel;

class Street extends Model
{
    protected $table = "streets";

    protected $guarded = [];

    public function bengkel()
    {
    	return $this->hasMany(Bengkel::class, 'street_id', 'id');
    }
}

app/Http/Controllers/StreetController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Street;

class StreetController extends Controller
{
    public function index()
    {
    	$streets = Street::all();
    	return view('streets.index', compact('streets'));
    }

    public function show($id)
    {
        $streets = Street::findOrFail($id);
        return view('streets.show', compact('streets'));
    }

    public function create()
    {
    	$streets = Street::all();
    	return view('streets.create', compact('streets'));
    }

    public function store(Request $request)
    {
    	$request->validate([
            'nama_jalan'    =>'required|min:5|max:300',
            'nama_daerah'   =>'required|min:5|max:200',
        ]);

        Street::create([
            'nama_jalan'    =>$request->nama_jalan,
            'nama_daerah'   =>$request->nama_daerah,
        ]);

        return redirect()->route('streets.index');
    }

    public function edit($id)
    {
        $streets = Street::findOrFail($id);
        return view('streets.edit', ['streets'=>$streets]);
    }

    public function update(Request $request, $id)
    {
        $streets = Street::findOrFail($id);
        $request->validate([
            'nama_jalan'    => 'required',
            'nama_daerah'   => 'required',
        ]);

        $streets->update([
            'nama_jalan'    => $request->nama_jalan,
            'nama_daerah'   => $request->nama_daerah,
        ]);

        $streets->save();
        return redirect()->route('streets.index', ['streets'=>$streets]);
    }

    public function destroy($id)
    {
        $streets = Street::findOrFail($id);
        $streets->delete();
        return redirect()->back();
    }
}

resources/views/streets/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
  <div class="card">
      <div class="card-header bg-success text-light">
          Create New Street
      </div>
      <div class="card-body">
        <form class="form-group" action="{{ route('streets.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
          <div class="row">
              <div class="col-md-2">
                  <label for="nama_jalan">Nama Jalan</label>
              </div>
              <div class="col-md-9">
                  <input type="text" class="form-control {{$errors->first('nama_jalan')? "is-invalid": ""}}" value=" {{ old('nama_jalan') }} " id="nama_jalan" name="nama_jalan">
                  <div class="invalid-feedback">
                    {{$errors->first('nama_jalan')}}
                  </div>
              </div>

          </div>
        <br>
          <div class="row">

              <div class="col-md-2">
                  <label for="nama_daerah">Nama Daerah</label>
              </div>
              <div class="col-md-9">
                  <input type="text" class="form-control {{$errors->first('nama_daerah')? "is-invalid": ""}}" value=" {{ old('nama_daerah') }} " id="nama_daerah" name="nama_daerah">
                  <div class="invalid-feedback">
                    {{$errors->first('nama_daerah')}}
                  </div>
              </div>
          </div>
        <br>
          <div class="row">
              <div class="col-md-3 offset-md-5 offset-md-4">
                  <button class="btn btn-outline-success" type="submit">Simpan</button>
              </div>
          </div>
        </form>
      </div>
  </div>
</div>

@endsection

resources/views/streets/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
    <div class="card">
        <div class="card-header bg-success text-light">
            Edit Street
        </div>

        <div class="card-body">
            <form class="form-group" action="{{ route('streets.update', $streets['id']) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')

                <div class="row">
                    <div class="col-md-2">
                        <label for="nama_jalan">Nama Jalan</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control {{$errors->first('nama_jalan')? "is-invalid": ""}}" id="nama_jalan" name="nama_jalan" value=" {{ old('nama_jalan') ? old('nama_jalan') : $streets['nama_jalan'] }} ">
                        <div class="invalid-feedback">
                          {{$errors->first('nama_jalan')}}
                        </div>
                    </div>
                </div>

              <br>

                <div class="row">
                    <div class="col-md-2">
                        <label for="nama_daerah">Nama Daerah</label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control {{$errors->first('nama_daerah')? "is-invalid": ""}}" id="nama_daerah" name="nama_daerah"  value=" {{ old('nama_daerah') ? old('nama_daerah') : $streets['nama_daerah'] }} ">
                        <div class="invalid-feedback">
                          {{$errors->first('nama_daerah')}}
                        </div>
                    </div>
                </div>

              <br>

                <div class="row">
                    <div class="col-md-3 offset-md-5 offset-md-4">
                        <button class="btn btn-outline-primary" type="submit">Simpan</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection

resources/views/streets/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
    <div class="card">
        <div class="card-header">
            Street
        </div>

        <div class="card-body">
            <a href="{{ route('streets.create') }}" class="btn btn-success"><span data-feather="plus-square"></span> Create new</a>
            <br><br>

                <div class="tabel-responsive">

                    <table class="table table-striped">

                        <thead>
                          <tr class="table-success">
                              <th>ID</th>
                              <th>Nama Jalan</th>
                              <th>Nama Daerah</th>
                              <th>Action</th>
                          </tr>
                        </thead>

                        <tbody>
                            @foreach($streets as $street)
                                <tr>
                                    <td> {{$street['id']}} </td>
                                    <td> {{$street['nama_jalan']}} </td>
                                    <td> {{$street['nama_daerah']}} </td>
                                    <td>
                                        <a href="{{ route('streets.show', ['id'=>$street['id']]) }}" class="btn-sm btn-success">Detail</a>
                                        <a href="{{ route('streets.edit', ['id'=>$street['id']]) }}" class="btn-sm btn-primary">Edit</a>

                                        <form action="{{ route('streets.destroy', ['id'=>$street['id']]) }}" method="POST" onsubmit="return confirm('Delete Permanen?')" class="d-inline">
                                        @csrf
                                        @method('DELETE')

                                          <button type="submit" class="btn-xs btn-danger" name="submit" value="Delete" style="border: none; border-radius: 3px;">
                                            Delete
                                          </button>

                                        </form>

                                    </td>
                                </tr>
                            @endforeach
                        </tbody>

                    </table>

                </div>

        </div>
    </div>
</div>

@endsection

resources/views/streets/show.blade.php
@extends('admin.layouts.app')

@section('title', 'Admin')

@section('content')

<div class="col-md-10">
	<div class="card">
		<div class="card-header bg-success text-light">
			Detail Street
		</div>

		<div class="card-body">

			<div class="row">
				<div class="col-md-2">
					<label for="nama_jalan">Nama Jalan</label>
				</div>
				<div class="col-md-9">
					<input type="text" readonly="" value="{{$streets['nama_jalan']}}" class="form-control">
				</div>
			</div>
		<br>
			<div class="row">
				<div class="col-md-2">
					<label for="nama_daerah">Nama  Daerah</label>
				</div>
				<div  class="col-md-9">
					<input type="text" value="{{$streets['nama_daerah']}}" class="form-control" readonly="">
				</div>
			</div>

		</div>

	</div>
</div>

@endsection