routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
});

Auth::routes();

Route::group(['prefix' => 'isAdmin', 'middleware' => ['admin', 'auth']], function(){
	Route::get('/admin', 'AdminController@index')->name('admin.index');
	Route::resource('users', 'UserController');
	Route::resource('bengkel', 'BengkelController');
	Route::resource('streets', 'StreetController');
});

Route::resource('home', 'HomeController');

resources/views/admin/layouts/_head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

resources/views/admin/layouts/_script.blade.php
<script src="{{ asset('js/app.js') }}" defer></script>
<script src="{{asset('js/feather.min.js')}}"></script>
<script>feather.replace()</script>

resources/views/admin/layouts/_topNav.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <span data-feather="codepen"></span> Bengkelin
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">Login</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">Register</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link active dropdown-toggle badge-success" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('admin.layouts._head')

<body>
    
    <div id="app">
        
        @include('admin.layouts._topNav')

        <main class="py-4">
        	<div class="container">

			    <div class="row">

			        <div class="col-md-2">
			            <div class="card">
			                <div class="card-header">
			                    <a href="{{ route('admin.index') }}" class="text-dark">Admin</a>
			                </div>
			                <div class="card-body">
			                    <ul class="nav flex-column">
			                        <li class="nav-item">
			                            <a href="{{ route('users.index') }}" class="nav-link">User</a>
			                            <a href="{{ route('bengkel.index') }}" class="nav-link">Bengkel</a>
			                            <a href="{{ route('streets.index') }}" class="nav-link">Street</a>
			                        </li>
			                    </ul>
			                </div>
			            </div>
			        </div>

			        @yield('content')

			    </div>

			</div>
            
        </main>
    </div>
@include('admin.layouts._script')
</body>
</html>